### ISSUE TITLE
unknown block tag: respimg

### ISSUE THREAD

**Issue by adamculpepper** [eeeps/eleventy-respimg#10]
@eeeps I found #6 and saw your comment for using #4's merged code, but I'm still getting the same error on my end.

```
TemplateWriterWriteError` was thrown
> (./_includes/layouts/home.njk) [Line 4, Column 6]
  unknown block tag: respimg

`Template render error` was thrown:
    Template render error: (./_includes/layouts/home.njk) [Line 4, Column 6]
      unknown block tag: respimg
        at Object._prettifyError (D:\repos\spectrumac-website\node_modules\nunjucks\src\lib.js:36:11)
        at Template.render (D:\repos\spectrumac-website\node_modules\nunjucks\src\environment.js:536:21)
        at D:\repos\spectrumac-website\node_modules\@11ty\eleventy\src\Engines\Nunjucks.js:236:14
        at new Promise (<anonymous>)
        at D:\repos\spectrumac-website\node_modules\@11ty\eleventy\src\Engines\Nunjucks.js:235:14
        at TemplateLayout.render (D:\repos\spectrumac-website\node_modules\@11ty\eleventy\src\TemplateLayout.js:152:31)
        at process._tickCallback (internal/process/next_tick.js:68:7)
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble writing template: _site/index.html
```

**Comment by adamculpepper** [comment]
I figured out what was happening here. I had to restart the server (`npx @11ty/eleventy --serve`) after modifying the `.eleventy.js` file and it worked beautifully! The `.eleventy.js` file was seemingly not updating at all even though the project was rebuilding.

**Comment by eeeps** [comment]
Great! Thanks for the feedback, sorry for the slow response, and glad it worked out.
