### ISSUE TITLE
error in DEBUG

### ISSUE THREAD

**Issue by GerhardMes** [eeeps/eleventy-respimg#6]
I have setup this cool script, but when trying to implement 

{% respimg
  "https://res.cloudinary.com/xxxx/image/upload/v1524743816/FODLER/IMAGE_NAME.jpg",
  "Lune Exacte - New Moon",
  "(min-width: 48em) 48em, 100vw"
%}

in markdown blog file; I am getting 

`File changed: site/blog/as_lune-exacte.md
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering njk (and markdown) template ./site/blog/as_lune-exacte.md (TemplateContentRenderError)
> (unknown path) [Line 22, Column 4]
  unknown block tag: respimg (Template render error):
    Template render error: (unknown path) [Line 22, Column 4]
      unknown block tag: respimg
        at Object._prettifyError (/Users/gXXX/eleventy/skeleventyStarter/node_modules/nunjucks/src/lib.js:36:11)
        at Template.render (/Users/XXX/eleventy/skeleventyStarter/node_modules/nunjucks/src/environment.js:542:21)
        at /Users/XXX/eleventy/skeleventyStarter/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:133:14
        at new Promise (<anonymous>)
        at /Users/gXXX/eleventy/skeleventyStarter/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:132:14
        at /Users/XXXe/eleventy/skeleventyStarter/node_modules/@11ty/eleventy/src/Engines/Markdown.js:65:47
        at Template.render (/Users/XXX/eleventy/skeleventyStarter/node_modules/@11ty/eleventy/src/TemplateContent.js:167:28)
        at processTicksAndRejections (internal/process/task_queues.js:89:5)
        at async Template._getContent (/Users/XXX/eleventy/skeleventyStarter/node_modules/@11ty/eleventy/src/Template.js:450:15)
        at async Template.getTertiaryMapEntry (/Users/XXX/eleventy/skeleventyStarter/node_modules/@11ty/eleventy/src/Template.js:622:24)
Copied 2 items and Processed 0 files in 0.55 seconds`

What have I made wrong? Any advice? 
I really would like to get this script up and running
Cheers Gerhard

**Comment by eeeps** [comment]
I'm hoping/guessing that this was the same problem that @paulrobertlloyd was having, which he fixed in https://github.com/eeeps/eleventy-respimg/pull/4, which I've just merged.

Can you try with the updated plugin?

**Comment by eeeps** [comment]
Closing during some end of the year housecleaning. Feel free to re-open if Paul's fix didn't work for you!
